b: 999
A: 1
hash:
  b: 999
  A: 1
  hoh:
    b: 999
    A: 1
  hol:
    a:
      - 2
      - 999
    b:
      - 998
      - 999
list:
  - b
  - A
  - B
lol:
  - 
    - A
    - B
    - C
  - 
    - d
    - e
    - f