b: 101
C: 1
hash:
  b: 101
  C: 1
  hoh:
    b: 101
    C: 1
  hol:
    a:
      - 2
      - 101
    b:
      - 101
      - 102
list:
  - b
  - C
lol:
  - 
    - D
    - E
    - F
  - 
    - d
    - e
    - f